# routes.yaml

home:
  path: /
  controller: App\Controller\ScoreController::index
  methods: GET

scores:
  path: /scores
  controller: App\Controller\ScoreController::scores
  methods: GET

create_score:
  path: /scores
  controller: App\Controller\ScoreController::createScore
  methods: POST
