# routes.yaml

home:
  path: /api/
  controller: App\Controller\ScoreController::index
  methods: GET

scores:
  path: /api/scores
  controller: App\Controller\ScoreController::scores
  methods: GET

create_score:
  path: /api/scores
  controller: App\Controller\ScoreController::createScore
  methods: POST

# Task routes
get_tasks:
  path: /api/tasks
  controller: App\Controller\TaskController::getTasks
  methods: GET

add_task:
  path: /api/tasks
  controller: App\Controller\TaskController::addTask
  methods: POST

get_task:
  path: /api/tasks/{id}
  controller: App\Controller\TaskController::getTask
  methods: GET

update_task:
  path: /api/tasks/{id}
  controller: App\Controller\TaskController::updateTask
  methods: PUT

delete_task:
  path: /api/tasks/{id}
  controller: App\Controller\TaskController::deleteTask
  methods: DELETE

search_tasks:
  path: /api/tasks-search
  controller: App\Controller\TaskController::search
  methods: GET

update_task_status:
  path: /api/tasks/{id}/status
  controller: App\Controller\TaskController::updateTaskStatus
  methods: POST
