name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PERSONAL_WEBSERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ec2-16-171-32-248.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Copy project to server
        run: |
          scp -r * ubuntu@ec2-16-171-32-248.eu-north-1.compute.amazonaws.com:/var/projects/general-api

      - name: Create .env and .env.production files on the server
        run: |
          ssh ubuntu@ec2-16-171-32-248.eu-north-1.compute.amazonaws.com << 'EOF'
            echo "APP_ENV=prod" > /var/projects/general-api/.env
            echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> /var/projects/general-api/.env
            echo "DATABASE_URL=${{ secrets.GENERAL_DATABASE_CONNECTION_STRING }}" >> /var/projects/general-api/.env
            echo "CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'" >> /var/projects/general-api/.env

            cp /var/projects/general-api/.env /var/projects/general-api/.env.production
          EOF

      - name: Install Composer dependencies on the server
        run: |
          ssh ubuntu@ec2-16-171-32-248.eu-north-1.compute.amazonaws.com << 'EOF'
            cd /var/projects/general-api
            composer install --no-interaction --prefer-dist --optimize-autoloader
          EOF

      - name: Ensure database exists
        run: |
          ssh ubuntu@ec2-16-171-32-248.eu-north-1.compute.amazonaws.com << 'EOF'
            cd /var/projects/general-api
            php bin/console doctrine:database:create --if-not-exists
          EOF

      - name: Run database migrations
        run: |
          ssh ubuntu@ec2-16-171-32-248.eu-north-1.compute.amazonaws.com << 'EOF'
            cd /var/projects/general-api
            php bin/console doctrine:migrations:migrate --no-interaction
          EOF
